// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person/person.proto

package com.test.protobuf.person;

public interface EducationInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:person.EducationInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string school = 1;</code>
   * @return The school.
   */
  java.lang.String getSchool();
  /**
   * <code>string school = 1;</code>
   * @return The bytes for school.
   */
  com.google.protobuf.ByteString
      getSchoolBytes();

  /**
   * <code>int32 year = 2;</code>
   * @return The year.
   */
  int getYear();
}
