// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person/person.proto

package com.test.protobuf.person;

/**
 * Protobuf type {@code person.Person}
 */
public  final class Person extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:person.Person)
    PersonOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Person.newBuilder() to construct.
  private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Person() {
    name_ = "";
    gender_ = 0;
    eduInfos_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Person();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Person(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 16: {

            age_ = input.readInt32();
            break;
          }
          case 25: {

            height_ = input.readDouble();
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            gender_ = rawValue;
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              eduInfos_ = new java.util.ArrayList<com.test.protobuf.person.EducationInfo>();
              mutable_bitField0_ |= 0x00000001;
            }
            eduInfos_.add(
                input.readMessage(com.test.protobuf.person.EducationInfo.parser(), extensionRegistry));
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              friendInfos_ = com.google.protobuf.MapField.newMapField(
                  FriendInfosDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            friendInfos__ = input.readMessage(
                FriendInfosDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            friendInfos_.getMutableMap().put(
                friendInfos__.getKey(), friendInfos__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        eduInfos_ = java.util.Collections.unmodifiableList(eduInfos_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.test.protobuf.person.PersonProto.internal_static_person_Person_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 6:
        return internalGetFriendInfos();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.test.protobuf.person.PersonProto.internal_static_person_Person_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.test.protobuf.person.Person.class, com.test.protobuf.person.Person.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AGE_FIELD_NUMBER = 2;
  private int age_;
  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  public int getAge() {
    return age_;
  }

  public static final int HEIGHT_FIELD_NUMBER = 3;
  private double height_;
  /**
   * <code>double height = 3;</code>
   * @return The height.
   */
  public double getHeight() {
    return height_;
  }

  public static final int GENDER_FIELD_NUMBER = 4;
  private int gender_;
  /**
   * <code>.person.Gender gender = 4;</code>
   * @return The enum numeric value on the wire for gender.
   */
  public int getGenderValue() {
    return gender_;
  }
  /**
   * <code>.person.Gender gender = 4;</code>
   * @return The gender.
   */
  public com.test.protobuf.common.Gender getGender() {
    @SuppressWarnings("deprecation")
    com.test.protobuf.common.Gender result = com.test.protobuf.common.Gender.valueOf(gender_);
    return result == null ? com.test.protobuf.common.Gender.UNRECOGNIZED : result;
  }

  public static final int EDU_INFOS_FIELD_NUMBER = 5;
  private java.util.List<com.test.protobuf.person.EducationInfo> eduInfos_;
  /**
   * <code>repeated .person.EducationInfo edu_infos = 5;</code>
   */
  public java.util.List<com.test.protobuf.person.EducationInfo> getEduInfosList() {
    return eduInfos_;
  }
  /**
   * <code>repeated .person.EducationInfo edu_infos = 5;</code>
   */
  public java.util.List<? extends com.test.protobuf.person.EducationInfoOrBuilder> 
      getEduInfosOrBuilderList() {
    return eduInfos_;
  }
  /**
   * <code>repeated .person.EducationInfo edu_infos = 5;</code>
   */
  public int getEduInfosCount() {
    return eduInfos_.size();
  }
  /**
   * <code>repeated .person.EducationInfo edu_infos = 5;</code>
   */
  public com.test.protobuf.person.EducationInfo getEduInfos(int index) {
    return eduInfos_.get(index);
  }
  /**
   * <code>repeated .person.EducationInfo edu_infos = 5;</code>
   */
  public com.test.protobuf.person.EducationInfoOrBuilder getEduInfosOrBuilder(
      int index) {
    return eduInfos_.get(index);
  }

  public static final int FRIEND_INFOS_FIELD_NUMBER = 6;
  private static final class FriendInfosDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.test.protobuf.person.PersonProto.internal_static_person_Person_FriendInfosEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> friendInfos_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetFriendInfos() {
    if (friendInfos_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          FriendInfosDefaultEntryHolder.defaultEntry);
    }
    return friendInfos_;
  }

  public int getFriendInfosCount() {
    return internalGetFriendInfos().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; friend_infos = 6;</code>
   */

  public boolean containsFriendInfos(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetFriendInfos().getMap().containsKey(key);
  }
  /**
   * Use {@link #getFriendInfosMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getFriendInfos() {
    return getFriendInfosMap();
  }
  /**
   * <code>map&lt;string, string&gt; friend_infos = 6;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getFriendInfosMap() {
    return internalGetFriendInfos().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; friend_infos = 6;</code>
   */

  public java.lang.String getFriendInfosOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetFriendInfos().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; friend_infos = 6;</code>
   */

  public java.lang.String getFriendInfosOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetFriendInfos().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (age_ != 0) {
      output.writeInt32(2, age_);
    }
    if (height_ != 0D) {
      output.writeDouble(3, height_);
    }
    if (gender_ != com.test.protobuf.common.Gender.UNKNOWN.getNumber()) {
      output.writeEnum(4, gender_);
    }
    for (int i = 0; i < eduInfos_.size(); i++) {
      output.writeMessage(5, eduInfos_.get(i));
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetFriendInfos(),
        FriendInfosDefaultEntryHolder.defaultEntry,
        6);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (age_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, age_);
    }
    if (height_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, height_);
    }
    if (gender_ != com.test.protobuf.common.Gender.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, gender_);
    }
    for (int i = 0; i < eduInfos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, eduInfos_.get(i));
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetFriendInfos().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      friendInfos__ = FriendInfosDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, friendInfos__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.test.protobuf.person.Person)) {
      return super.equals(obj);
    }
    com.test.protobuf.person.Person other = (com.test.protobuf.person.Person) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (getAge()
        != other.getAge()) return false;
    if (java.lang.Double.doubleToLongBits(getHeight())
        != java.lang.Double.doubleToLongBits(
            other.getHeight())) return false;
    if (gender_ != other.gender_) return false;
    if (!getEduInfosList()
        .equals(other.getEduInfosList())) return false;
    if (!internalGetFriendInfos().equals(
        other.internalGetFriendInfos())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + AGE_FIELD_NUMBER;
    hash = (53 * hash) + getAge();
    hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getHeight()));
    hash = (37 * hash) + GENDER_FIELD_NUMBER;
    hash = (53 * hash) + gender_;
    if (getEduInfosCount() > 0) {
      hash = (37 * hash) + EDU_INFOS_FIELD_NUMBER;
      hash = (53 * hash) + getEduInfosList().hashCode();
    }
    if (!internalGetFriendInfos().getMap().isEmpty()) {
      hash = (37 * hash) + FRIEND_INFOS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetFriendInfos().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.test.protobuf.person.Person parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.test.protobuf.person.Person parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.test.protobuf.person.Person parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.test.protobuf.person.Person parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.test.protobuf.person.Person parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.test.protobuf.person.Person parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.test.protobuf.person.Person parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.test.protobuf.person.Person parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.test.protobuf.person.Person parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.test.protobuf.person.Person parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.test.protobuf.person.Person parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.test.protobuf.person.Person parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.test.protobuf.person.Person prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code person.Person}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:person.Person)
      com.test.protobuf.person.PersonOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.test.protobuf.person.PersonProto.internal_static_person_Person_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetFriendInfos();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetMutableFriendInfos();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.test.protobuf.person.PersonProto.internal_static_person_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.test.protobuf.person.Person.class, com.test.protobuf.person.Person.Builder.class);
    }

    // Construct using com.test.protobuf.person.Person.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEduInfosFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      age_ = 0;

      height_ = 0D;

      gender_ = 0;

      if (eduInfosBuilder_ == null) {
        eduInfos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        eduInfosBuilder_.clear();
      }
      internalGetMutableFriendInfos().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.test.protobuf.person.PersonProto.internal_static_person_Person_descriptor;
    }

    @java.lang.Override
    public com.test.protobuf.person.Person getDefaultInstanceForType() {
      return com.test.protobuf.person.Person.getDefaultInstance();
    }

    @java.lang.Override
    public com.test.protobuf.person.Person build() {
      com.test.protobuf.person.Person result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.test.protobuf.person.Person buildPartial() {
      com.test.protobuf.person.Person result = new com.test.protobuf.person.Person(this);
      int from_bitField0_ = bitField0_;
      result.name_ = name_;
      result.age_ = age_;
      result.height_ = height_;
      result.gender_ = gender_;
      if (eduInfosBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          eduInfos_ = java.util.Collections.unmodifiableList(eduInfos_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.eduInfos_ = eduInfos_;
      } else {
        result.eduInfos_ = eduInfosBuilder_.build();
      }
      result.friendInfos_ = internalGetFriendInfos();
      result.friendInfos_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.test.protobuf.person.Person) {
        return mergeFrom((com.test.protobuf.person.Person)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.test.protobuf.person.Person other) {
      if (other == com.test.protobuf.person.Person.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getAge() != 0) {
        setAge(other.getAge());
      }
      if (other.getHeight() != 0D) {
        setHeight(other.getHeight());
      }
      if (other.gender_ != 0) {
        setGenderValue(other.getGenderValue());
      }
      if (eduInfosBuilder_ == null) {
        if (!other.eduInfos_.isEmpty()) {
          if (eduInfos_.isEmpty()) {
            eduInfos_ = other.eduInfos_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEduInfosIsMutable();
            eduInfos_.addAll(other.eduInfos_);
          }
          onChanged();
        }
      } else {
        if (!other.eduInfos_.isEmpty()) {
          if (eduInfosBuilder_.isEmpty()) {
            eduInfosBuilder_.dispose();
            eduInfosBuilder_ = null;
            eduInfos_ = other.eduInfos_;
            bitField0_ = (bitField0_ & ~0x00000001);
            eduInfosBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEduInfosFieldBuilder() : null;
          } else {
            eduInfosBuilder_.addAllMessages(other.eduInfos_);
          }
        }
      }
      internalGetMutableFriendInfos().mergeFrom(
          other.internalGetFriendInfos());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.test.protobuf.person.Person parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.test.protobuf.person.Person) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int age_ ;
    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    public int getAge() {
      return age_;
    }
    /**
     * <code>int32 age = 2;</code>
     * @param value The age to set.
     * @return This builder for chaining.
     */
    public Builder setAge(int value) {
      
      age_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 age = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAge() {
      
      age_ = 0;
      onChanged();
      return this;
    }

    private double height_ ;
    /**
     * <code>double height = 3;</code>
     * @return The height.
     */
    public double getHeight() {
      return height_;
    }
    /**
     * <code>double height = 3;</code>
     * @param value The height to set.
     * @return This builder for chaining.
     */
    public Builder setHeight(double value) {
      
      height_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double height = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeight() {
      
      height_ = 0D;
      onChanged();
      return this;
    }

    private int gender_ = 0;
    /**
     * <code>.person.Gender gender = 4;</code>
     * @return The enum numeric value on the wire for gender.
     */
    public int getGenderValue() {
      return gender_;
    }
    /**
     * <code>.person.Gender gender = 4;</code>
     * @param value The enum numeric value on the wire for gender to set.
     * @return This builder for chaining.
     */
    public Builder setGenderValue(int value) {
      gender_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.person.Gender gender = 4;</code>
     * @return The gender.
     */
    public com.test.protobuf.common.Gender getGender() {
      @SuppressWarnings("deprecation")
      com.test.protobuf.common.Gender result = com.test.protobuf.common.Gender.valueOf(gender_);
      return result == null ? com.test.protobuf.common.Gender.UNRECOGNIZED : result;
    }
    /**
     * <code>.person.Gender gender = 4;</code>
     * @param value The gender to set.
     * @return This builder for chaining.
     */
    public Builder setGender(com.test.protobuf.common.Gender value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      gender_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.person.Gender gender = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearGender() {
      
      gender_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.test.protobuf.person.EducationInfo> eduInfos_ =
      java.util.Collections.emptyList();
    private void ensureEduInfosIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        eduInfos_ = new java.util.ArrayList<com.test.protobuf.person.EducationInfo>(eduInfos_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.test.protobuf.person.EducationInfo, com.test.protobuf.person.EducationInfo.Builder, com.test.protobuf.person.EducationInfoOrBuilder> eduInfosBuilder_;

    /**
     * <code>repeated .person.EducationInfo edu_infos = 5;</code>
     */
    public java.util.List<com.test.protobuf.person.EducationInfo> getEduInfosList() {
      if (eduInfosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(eduInfos_);
      } else {
        return eduInfosBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .person.EducationInfo edu_infos = 5;</code>
     */
    public int getEduInfosCount() {
      if (eduInfosBuilder_ == null) {
        return eduInfos_.size();
      } else {
        return eduInfosBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .person.EducationInfo edu_infos = 5;</code>
     */
    public com.test.protobuf.person.EducationInfo getEduInfos(int index) {
      if (eduInfosBuilder_ == null) {
        return eduInfos_.get(index);
      } else {
        return eduInfosBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .person.EducationInfo edu_infos = 5;</code>
     */
    public Builder setEduInfos(
        int index, com.test.protobuf.person.EducationInfo value) {
      if (eduInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEduInfosIsMutable();
        eduInfos_.set(index, value);
        onChanged();
      } else {
        eduInfosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .person.EducationInfo edu_infos = 5;</code>
     */
    public Builder setEduInfos(
        int index, com.test.protobuf.person.EducationInfo.Builder builderForValue) {
      if (eduInfosBuilder_ == null) {
        ensureEduInfosIsMutable();
        eduInfos_.set(index, builderForValue.build());
        onChanged();
      } else {
        eduInfosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .person.EducationInfo edu_infos = 5;</code>
     */
    public Builder addEduInfos(com.test.protobuf.person.EducationInfo value) {
      if (eduInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEduInfosIsMutable();
        eduInfos_.add(value);
        onChanged();
      } else {
        eduInfosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .person.EducationInfo edu_infos = 5;</code>
     */
    public Builder addEduInfos(
        int index, com.test.protobuf.person.EducationInfo value) {
      if (eduInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEduInfosIsMutable();
        eduInfos_.add(index, value);
        onChanged();
      } else {
        eduInfosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .person.EducationInfo edu_infos = 5;</code>
     */
    public Builder addEduInfos(
        com.test.protobuf.person.EducationInfo.Builder builderForValue) {
      if (eduInfosBuilder_ == null) {
        ensureEduInfosIsMutable();
        eduInfos_.add(builderForValue.build());
        onChanged();
      } else {
        eduInfosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .person.EducationInfo edu_infos = 5;</code>
     */
    public Builder addEduInfos(
        int index, com.test.protobuf.person.EducationInfo.Builder builderForValue) {
      if (eduInfosBuilder_ == null) {
        ensureEduInfosIsMutable();
        eduInfos_.add(index, builderForValue.build());
        onChanged();
      } else {
        eduInfosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .person.EducationInfo edu_infos = 5;</code>
     */
    public Builder addAllEduInfos(
        java.lang.Iterable<? extends com.test.protobuf.person.EducationInfo> values) {
      if (eduInfosBuilder_ == null) {
        ensureEduInfosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, eduInfos_);
        onChanged();
      } else {
        eduInfosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .person.EducationInfo edu_infos = 5;</code>
     */
    public Builder clearEduInfos() {
      if (eduInfosBuilder_ == null) {
        eduInfos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        eduInfosBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .person.EducationInfo edu_infos = 5;</code>
     */
    public Builder removeEduInfos(int index) {
      if (eduInfosBuilder_ == null) {
        ensureEduInfosIsMutable();
        eduInfos_.remove(index);
        onChanged();
      } else {
        eduInfosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .person.EducationInfo edu_infos = 5;</code>
     */
    public com.test.protobuf.person.EducationInfo.Builder getEduInfosBuilder(
        int index) {
      return getEduInfosFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .person.EducationInfo edu_infos = 5;</code>
     */
    public com.test.protobuf.person.EducationInfoOrBuilder getEduInfosOrBuilder(
        int index) {
      if (eduInfosBuilder_ == null) {
        return eduInfos_.get(index);  } else {
        return eduInfosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .person.EducationInfo edu_infos = 5;</code>
     */
    public java.util.List<? extends com.test.protobuf.person.EducationInfoOrBuilder> 
         getEduInfosOrBuilderList() {
      if (eduInfosBuilder_ != null) {
        return eduInfosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(eduInfos_);
      }
    }
    /**
     * <code>repeated .person.EducationInfo edu_infos = 5;</code>
     */
    public com.test.protobuf.person.EducationInfo.Builder addEduInfosBuilder() {
      return getEduInfosFieldBuilder().addBuilder(
          com.test.protobuf.person.EducationInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .person.EducationInfo edu_infos = 5;</code>
     */
    public com.test.protobuf.person.EducationInfo.Builder addEduInfosBuilder(
        int index) {
      return getEduInfosFieldBuilder().addBuilder(
          index, com.test.protobuf.person.EducationInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .person.EducationInfo edu_infos = 5;</code>
     */
    public java.util.List<com.test.protobuf.person.EducationInfo.Builder> 
         getEduInfosBuilderList() {
      return getEduInfosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.test.protobuf.person.EducationInfo, com.test.protobuf.person.EducationInfo.Builder, com.test.protobuf.person.EducationInfoOrBuilder> 
        getEduInfosFieldBuilder() {
      if (eduInfosBuilder_ == null) {
        eduInfosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.test.protobuf.person.EducationInfo, com.test.protobuf.person.EducationInfo.Builder, com.test.protobuf.person.EducationInfoOrBuilder>(
                eduInfos_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        eduInfos_ = null;
      }
      return eduInfosBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> friendInfos_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetFriendInfos() {
      if (friendInfos_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            FriendInfosDefaultEntryHolder.defaultEntry);
      }
      return friendInfos_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableFriendInfos() {
      onChanged();;
      if (friendInfos_ == null) {
        friendInfos_ = com.google.protobuf.MapField.newMapField(
            FriendInfosDefaultEntryHolder.defaultEntry);
      }
      if (!friendInfos_.isMutable()) {
        friendInfos_ = friendInfos_.copy();
      }
      return friendInfos_;
    }

    public int getFriendInfosCount() {
      return internalGetFriendInfos().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; friend_infos = 6;</code>
     */

    public boolean containsFriendInfos(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetFriendInfos().getMap().containsKey(key);
    }
    /**
     * Use {@link #getFriendInfosMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getFriendInfos() {
      return getFriendInfosMap();
    }
    /**
     * <code>map&lt;string, string&gt; friend_infos = 6;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getFriendInfosMap() {
      return internalGetFriendInfos().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; friend_infos = 6;</code>
     */

    public java.lang.String getFriendInfosOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetFriendInfos().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; friend_infos = 6;</code>
     */

    public java.lang.String getFriendInfosOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetFriendInfos().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearFriendInfos() {
      internalGetMutableFriendInfos().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; friend_infos = 6;</code>
     */

    public Builder removeFriendInfos(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableFriendInfos().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableFriendInfos() {
      return internalGetMutableFriendInfos().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; friend_infos = 6;</code>
     */
    public Builder putFriendInfos(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableFriendInfos().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; friend_infos = 6;</code>
     */

    public Builder putAllFriendInfos(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableFriendInfos().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:person.Person)
  }

  // @@protoc_insertion_point(class_scope:person.Person)
  private static final com.test.protobuf.person.Person DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.test.protobuf.person.Person();
  }

  public static com.test.protobuf.person.Person getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Person>
      PARSER = new com.google.protobuf.AbstractParser<Person>() {
    @java.lang.Override
    public Person parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Person(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Person> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Person> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.test.protobuf.person.Person getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

