// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person/person.proto

package com.test.protobuf.person;

public final class PersonProto {
  private PersonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_person_EducationInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_person_EducationInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_person_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_person_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_person_Person_FriendInfosEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_person_Person_FriendInfosEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023person/person.proto\022\006person\032\023person/co" +
      "mmon.proto\"-\n\rEducationInfo\022\016\n\006school\030\001 " +
      "\001(\t\022\014\n\004year\030\002 \001(\005\"\350\001\n\006Person\022\014\n\004name\030\001 \001" +
      "(\t\022\013\n\003age\030\002 \001(\005\022\016\n\006height\030\003 \001(\001\022\036\n\006gende" +
      "r\030\004 \001(\0162\016.person.Gender\022(\n\tedu_infos\030\005 \003" +
      "(\0132\025.person.EducationInfo\0225\n\014friend_info" +
      "s\030\006 \003(\0132\037.person.Person.FriendInfosEntry" +
      "\0322\n\020FriendInfosEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005val" +
      "ue\030\002 \001(\t:\0028\001B)\n\030com.test.protobuf.person" +
      "B\013PersonProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.test.protobuf.common.CommonProto.getDescriptor(),
        });
    internal_static_person_EducationInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_person_EducationInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_person_EducationInfo_descriptor,
        new java.lang.String[] { "School", "Year", });
    internal_static_person_Person_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_person_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_person_Person_descriptor,
        new java.lang.String[] { "Name", "Age", "Height", "Gender", "EduInfos", "FriendInfos", });
    internal_static_person_Person_FriendInfosEntry_descriptor =
      internal_static_person_Person_descriptor.getNestedTypes().get(0);
    internal_static_person_Person_FriendInfosEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_person_Person_FriendInfosEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.test.protobuf.common.CommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
